version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        
        databases:
          default:
            connector: postgres
            host: ec2-54-155-208-5.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: dfbbg7ur9g12eh
            ssl: true
            user: ioijdzsoysygsx
            password: 2d41ff34febbf6175c5028564b2f02b924157ec1c3246d0f6e7c56e248ff0dd4
            migrations: true